#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
	echo "No xdg config home"
	echo "Using ~/.config"
	XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
	echo "Error: No DEV_ENV variable set"
	exit 0
fi

while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	else
		filter="$1"
	fi
	shift
done

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

execute() {
	log "execute: $@"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

log "--------- dev-end ----------"

update_files() {
	from=$1
	to=$2

	pushd $from > /dev/null
	dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
	for dir in $dirs; do
		execute rm -rf $to/$(basename "$dir")
		execute cp -r $dir $to/$(basename "$dir")
	done
	popd > /dev/null
}

copy() {
	log "removing: $2"

	execute rm "$2"
	execute cp "$1" "$2"
}

update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME
update_files $DEV_ENV/env/.local $HOME/.local

copy $HOME/personal/tmux-sessionizer/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
copy $DEV_ENV/env/.zshrc $HOME/.zshrc
copy $DEV_ENV/env/.zsh_profile $HOME/.zsh_profile
copy $DEV_ENV/env/.tmux-sessionizer $HOME/.tmux-sessionizer
copy $DEV_ENV/dev-env $HOME/.local/scripts/dev-env
