#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

cd $script_dir
scripts=$(find $script_dir/runs -maxdepth 1 -mindepth 1 -executable -type f)

# Indentify which OS the script is running on
if [[ -f /etc/os-release ]]; then
    source /etc/os-release
    OS=$ID
	export OS
fi

while [[ $# -gt 0 ]]; do
	echo "ARG: \"$1\""
	if [[ $1 == "--dry" ]]; then
		dry="1"
	else
		filter="$1"
	fi
	shift
done

export dry

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

execute() {
	log "execute: $@"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

log "run: filter=$filter"

for script in $scripts; do
	if echo "$script" | grep -qv "$filter"; then
		log "filtered: $filter -- $script"
		continue
	fi
	log "running script: $script"
	execute $script
done
