#!/usr/bin/env bash

echo "⬇️ Downloading i3"

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/utils.sh

if [[ $ID == "arch" ]]; then
	execute sudo pacman -S --needed i3 i3-wm
else
	execute sudo apt install i3 i3-wm
fi
