#!/usr/bin/env bash

echo "⬇️ Downloading polybar/waybar..."

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/utils.sh

if [[ $OS == "arch" ]]; then
	execute sudo pacman -S --needed waybar
else
	execute sudo apt install -y polybar
fi
