#!/usr/bin/env bash

echo "⬇️ Downloading polybar..."

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/utils.sh

if [[ $ID == "arch" ]]; then
	execute sudo pacman -S --needed polybar
else
	execute sudo apt install -y polybar
fi
